name: 'what-changes'
description: 'Report what changes within branches'
author: 'classfunc'

# Define your inputs here.
inputs:
  owner:
    description: "repo's owner"
    required: false
    default: '${{ github.event.repository.owner.login }}'
  repo:
    description: "repo name"
    required: false
    default: '${{ github.event.repository.name }}'
  pr:
    description: "pull request number"
    required: false
    default: '${{ github.event.number }}'
  output-type:
    description: "output type"
    required: false
    default: 'md'
  pr-title:
    description: "pull request title"
    required: false
    default: '${{ github.event.pull_request.title }}'

# Define your outputs here.
outputs:
  value:
    description: 'value of var `output-type` field'
  total:
    description: 'total number of changes'
  numOfMerged:
    description: 'number of merged pull requests'
  numOfHotfix:
    description: 'number of hotfix commits'
  summary:
    description: 'summary of changes'

runs:
  using: node20
  main: dist/index.js
