name: 'what-changes'
description: 'Report what changes within branches'
author: 'classfunc'

# Define your inputs here.
inputs:
  owner:
    description: "repo's owner"
    required: false
    default: '${{ github.event.repository.owner.login }}'
  repo:
    description: "repo name"
    required: false
    default: '${{ github.event.repository.name }}'
  pr:
    description: "pull request number"
    required: false
    default: '${{ github.event.number }}'
  output-type:
    description: "output type"
    required: false
    default: 'html'

# Define your outputs here.
outputs:
  value:
    description: 'value of var `output-type` field'

runs:
  using: node20
  main: dist/index.js
